#pragma once
#include "stdafx.h"

enum eNetworkEntityType : uint8_t
{
	NETWORK_ENTITY_TYPE_PLAYER,
	NETWORK_ENTITY_TYPE_NOTHING,
	NETWORK_ENTITY_TYPE_BUILDING,
	NETWORK_ENTITY_TYPE_VEHICLE,
	NETWORK_ENTITY_TYPE_PED,
	NETWORK_ENTITY_TYPE_OBJECT,
	NETWORK_ENTITY_TYPE_DUMMY,
	NETWORK_ENTITY_TYPE_NOTINPOOLS
};

extern inline const char* eNetworkEntityTypeToString(eNetworkEntityType type)
{
	static const char* str[] = {
		"NETWORK_ENTITY_TYPE_PLAYER",
		"NETWORK_ENTITY_TYPE_NOTHING",
		"NETWORK_ENTITY_TYPE_BUILDING",
		"NETWORK_ENTITY_TYPE_VEHICLE",
		"NETWORK_ENTITY_TYPE_PED",
		"NETWORK_ENTITY_TYPE_OBJECT",
		"NETWORK_ENTITY_TYPE_DUMMY",
		"NETWORK_ENTITY_TYPE_NOTINPOOLS"
	};
	if (type < NETWORK_ENTITY_TYPE_PLAYER || type > NETWORK_ENTITY_TYPE_NOTINPOOLS)
	{
		return "(null)";
	}
	return str[type];
}