#pragma once

#ifndef _CPACKET_H_
	#define _CPACKET_H_

enum CPacketsID : unsigned short
{
	CHECK_VERSION = 0, // reserved but not used, see enet_host_connect
	PLAYER_CONNECTED,
	PLAYER_DISCONNECTED,
	PLAYER_ONFOOT,
	PLAYER_BULLET_SHOT,
	PLAYER_HANDSHAKE,
	PLAYER_PLACE_WAYPOINT,
	PLAYER_GET_NAME,
	VEHICLE_SPAWN,
	PLAYER_SET_HOST,
	ADD_EXPLOSION,
	VEHICLE_REMOVE,
	VEHICLE_IDLE_UPDATE,
	VEHICLE_DRIVER_UPDATE,
	VEHICLE_ENTER,
	VEHICLE_EXIT,
	VEHICLE_DAMAGE,
	VEHICLE_COMPONENT_ADD,
	VEHICLE_COMPONENT_REMOVE,
	VEHICLE_PASSENGER_UPDATE,
	PLAYER_CHAT_MESSAGE,
	PED_SPAWN,
	PED_REMOVE,
	PED_ONFOOT,
	GAME_WEATHER_TIME,
	PED_ADD_TASK,
	PED_REMOVE_TASK,
	PLAYER_KEY_SYNC,
	PED_DRIVER_UPDATE,
	PED_SHOT_SYNC,
	PED_PASSENGER_UPDATE,
	PLAYER_AIM_SYNC,
	VEHICLE_CONFIRM,
	PED_CONFIRM,
	PLAYER_STATS,
	REBUILD_PLAYER,
	RESPAWN_PLAYER,
	ASSIGN_VEHICLE,
	MASS_PACKET_SEQUENCE,
	START_CUTSCENE,
	SKIP_CUTSCENE,
	OPCODE_SYNC,
	ON_MISSION_FLAG_SYNC,
	UPDATE_ENTITY_BLIP,
	REMOVE_ENTITY_BLIP,
	ADD_MESSAGE_GXT,
	REMOVE_MESSAGE_GXT,
	CLEAR_ENTITY_BLIPS,
	PLAY_MISSION_AUDIO,
	UPDATE_CHECKPOINT,
	REMOVE_CHECKPOINT,
	ENEX_SYNC,
	CREATE_STATIC_BLIP,
	PACKET_ID_MAX
};


#endif