#if !defined(_COOPSERVER_NETWORK_NETWORKENTITYTYPE_H_) || !defined(_COOPSERVER_NETWORKENTITYTYPE_H_)
#define _COOPSERVER_NETWORK_NETWORKENTITYTYPE_H_
#define _COOPSERVER_NETWORKENTITYTYPE_H_

#include <cstdint>

enum eNetworkEntityType : uint8_t
{
	NETWORK_ENTITY_TYPE_PLAYER,
	NETWORK_ENTITY_TYPE_NOTHING,
	NETWORK_ENTITY_TYPE_BUILDING,
	NETWORK_ENTITY_TYPE_VEHICLE,
	NETWORK_ENTITY_TYPE_PED,
	NETWORK_ENTITY_TYPE_OBJECT,
	NETWORK_ENTITY_TYPE_DUMMY,
	NETWORK_ENTITY_TYPE_NOTINPOOLS
};

#endif