using GTASDK;
using GTASDK.ViceCity;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Runtime.InteropServices;

namespace CoopAndreasNET.SDK
{
    public class Scripting
    {

        [DllImport("GameSDK.asi", CallingConvention = CallingConvention.Cdecl)]
        /// <summary>
        ///  функция для вызова опкодов без v аргумента, если он есть, создаем функцию для него в scripting.cpp
        /// </summary>
        /// <param name="opcode">опкод</param>
        /// <param name="args">типы аргументов ("iifffi" - пример), i - int, f - float, s - string, v и z не трогаем, для них создаем функцию отдельно (scripting.cpp)</param>
        /// <param name="__arglist">аргументы, __arglist(arg1, arg2, ..., argN), массив передать нельзя</param>
        /// <returns>результат условия, например is_model_available, 1 - если модель загружена, 0 - иначе</returns>
        public static extern int ScriptCommand(ushort opcode, string args, __arglist);

        #region Actors
        [DllImport("GameSDK.asi", CallingConvention = CallingConvention.Cdecl)]
        public static extern int opcode_create_actor(int pedType, int model, float x, float y, float z, ref uint id); // create actor (ped)

        // ----------------------------------------------------------------------------------------------------------------------------

        [DllImport("GameSDK.asi", CallingConvention = CallingConvention.Cdecl)]
        public static extern int opcode_get_actor_pos(uint id, ref float x, ref float y, ref float z); // get actor pos(ped)

        // ----------------------------------------------------------------------------------------------------------------------------

        [DllImport("GameSDK.asi", CallingConvention = CallingConvention.Cdecl)]
        public static extern int opcode_get_actor_ptr(uint id, ref uint ptr); // get actor pointer (ped)

        // ----------------------------------------------------------------------------------------------------------------------------
        
        [DllImport("GameSDK.asi", CallingConvention = CallingConvention.Cdecl)]
        public static extern int opcode_create_player(ref uint iPlayerNum, float fX, float fY, float fZ, ref uint dwPlayerActorID); // create player ped for other players

        // ----------------------------------------------------------------------------------------------------------------------------
        
        [DllImport("GameSDK.asi", CallingConvention = CallingConvention.Cdecl)]
        public static extern int opcode_create_actor_from_player(ref uint iPlayerNum, ref uint dwPlayerActorID); // get actor pointer (ped)
        #endregion
    }
    public enum Command : ushort
    {
        // tasks
        actor_task_goto_point = 0x05D3,
        //...
        create_arrow_above_actor = 0x0187,
        set_player_skin = 0x09C7,
        request_model = 0x0247,
        load_requested_models = 0x038B,
        create_car = 0x00A5,
        load_special_actor = 0x023C,
        create_actor = 0x009A,
        destroy_actor_fading = 0x034F,
        destroy_actor = 0x009b,
        set_weather = 0x01B6,
        set_fade_color = 0x0169,
        fade = 0x016A,
        is_fading = 0x016B,
        freeze_player = 0x01B4,
        name_thread = 0x03A4,
        set_max_wanted_level = 0x01F0,
        set_wasted_busted_check = 0x0111,
        set_current_time = 0x00C0,
        get_current_time = 0x00C0,
        refresh_screen = 0x04E4,
        set_camera = 0x03CB,
        create_player = 0x0053,
        create_actor_from_player = 0x01F5,
        set_actor_skin = 0x0352,
        refresh_actor_skin = 0x0353,
        select_interior = 0x04BB,
        make_actor_leave_vehicle = 0x03E2,
        clear_actor_objective = 0x011C,
        set_car_color = 0x0229,
        wait = 0x0001,
        create_thread = 0x00D7,
        end_thread = 0x004E,
        destroy_car = 0x00A6,
        set_car_z_angle = 0x0175,
        car_relative_coordinates = 0x0407,
        set_car_max_speed = 0x00AD,
        is_model_available = 0x0248,
        create_actor_in_driverseat = 0x0129,
        create_actor_in_passenger = 0x01c8,
        drive_car_to_point1 = 0x02c2,
        car_ignore_traffic = 0x00AE,
        set_car_immune_to_nonplayer = 0x02aa,
        give_actor_weapon = 0x01B2,
        reset_actor_flags = 0x01ED,
        set_actor_ped_stats = 0x0243,
        toggle_actor_wander = 0x0319,
        play_music = 0x0394,
        clear_player_wanted_level = 0x0110,
        set_car_door_status = 0x020A,
        remove_references_to_actor = 0x01C2,
        remove_references_to_car = 0x01C3,
        set_player_wanted_level = 0x010D,
        set_player_health = 0x0222,
        get_car_health = 0x0227,
        text_styled = 0x00BA,
        text_now = 0x00BC,
        text_1number_styled = 0x01E3,
        toggle_car_siren = 0x0397,
        toggle_widescreen = 0x02A3,
        set_camera_behind_player = 0x0373,
        camera_on_player = 0x0157,
        camera_on_vehicle = 0x0158,
        camera_on_actor = 0x0159,
        restore_camera = 0x015A,
        point_camera = 0x0160,
        restore_camera_jumpcut = 0x02EB,
        set_camera_position = 0x015F,
        tie_actor_to_player = 0x01DF,
        tie_marker_to_car = 0x0161,
        tie_marker_to_actor = 0x0162,
        disable_marker = 0x0164,
        set_marker_color = 0x0165,
        set_marker_brightness = 0x0166,
        create_marker = 0x0167,
        create_radar_marker_without_sphere = 0x04CE,
        show_on_radar = 0x0168,
        set_car_driver_behaviour = 0x00AF,
        set_actor_to_kill_actor = 0x01C9,
        set_actor_to_kill_player = 0x01CA,
        is_actor_dead = 0x0118,
        player_near_point_on_foot = 0x00F6,
        create_icon_marker_sphere = 0x02A7,
        is_player_near_point_3d = 0x00F5,
        is_actor_near_point_3d = 0x00FE,
        is_car_near_point_3d = 0x01AF,
        set_player_z_angle = 0x0171,
        give_player_weapon = 0x01B1,
        get_line_of_sight = 0x06BD,
        add_to_player_money = 0x0109,
        get_player_money = 0x010b,
        restart_if_busted_at = 0x016D,
        is_marker_enabled = 0x075c,
        has_car_sunk = 0x02bf,
        is_car_wrecked = 0x0119,
        get_ground_z = 0x02ce,
        create_checkpoint1 = 0x0189,
        create_checkpoint2 = 0x018a,
        create_racing_checkpoint = 0x06d5,
        destroy_racing_checkpoint = 0x06d6,
        restart_if_wasted_at = 0x016C,
        toggle_player_infinite_run = 0x0330,
        toggle_player_controllable = 0x01B4,
        toggle_player_fast_reload = 0x0331,
        set_actor_armed_weapon = 0x01b9,
        get_actor_armed_weapon = 0x0470,
        remove_player_weapons = 0x03b8,
        put_actor_in_car = 0x036A,
        put_player_at_and_remove_from_car = 0x012a,
        set_actor_immunities = 0x02ab,
        set_car_immunities = 0x02ac,
        set_actor_can_be_decapitated = 0x0446,
        create_object = 0x0107,
        set_object_z_angle = 0x0177,
        set_object_rotation = 0x0453,
        set_object_collision = 0x0382,
        put_object_at = 0x01Bc,
        move_object = 0x034e,
        make_object_moveable = 0x0392,
        toggle_object_collision = 0x0382,
        play_sound = 0x018c,
        create_sound = 0x018d,
        remove_actor_from_car_and_put_at = 0x0362,
        send_actor_to_car_driverseat = 0x05CB,
        send_actor_to_car_passenger = 0x05CA,
        make_actor_leave_car = 0x05CD,
        get_car_z_angle = 0x0174,
        get_player_z_angle = 0x0170,
        create_train = 0x06D8,
        destroy_train = 0x07bd,
        set_train_acceleration = 0x06DC,
        set_train_speed = 0x06DD,
        set_vehicle_speed = 0x04BA,
        is_train_wrecked = 0x0981,
        actor_driving_train = 0x09AE,
        enable_train_traffic = 0x06d7,
        unknown_train_attr = 0x0A07,
        car_gas_tank_explosion = 0x09C4,
        lock_car = 0x0519,
        put_train_at = 0x07c7,
        turn_off_car_engine = 0x02d4,
        release_model = 0x0249,
        get_active_interior = 0x077e,
        get_actor_z_angle = 0x0172,
        set_actor_z_angle = 0x0173,
        actor_set_collision = 0x0619,
        actor_unknown1 = 0x094f,
        toggle_player_ignored_by_all = 0x03bf,
        enter_passenger_driveby = 0x0713,
        lock_actor = 0x04d7,
        refresh_streaming_at = 0x04E4,
        put_actor_in_car2 = 0x0430,
        toggle_vehicle_headlights = 0x067F,
        drive_car_to_point = 0x05D1,
        toggle_goggles = 0x09EB,
        kill_actor = 0x0321,
        set_actor_animation_set = 0x0245,
        request_animation = 0x04ED,
        is_animation_loaded = 0x04EE,
        release_animation = 0x04EF,
        apply_animation = 0x0812,
        is_actor_performing_anim = 0x0611,
        set_actor_weapon_droppable = 0x087e,
        set_actor_money = 0x03fe,
        toggle_radar_blank = 0x0581,
        text_clear_all = 0x00be,
        link_actor_to_interior = 0x0860,
        repair_car = 0x0A30,
        toggle_player_trapped_incar = 0x07cc,
        set_car_hydraulics = 0x07FF,
        toggle_player_weapons_changable = 0x0992,
        apply_object_animation = 0x075a,
        remove_weapon_from_actor = 0x0555,
        get_actor_move_velocity = 0x083d,
        get_actor_distance_from_ground = 0x0819,
        is_actor_falling_think = 0x0818,
        attach_object_to_actor = 0x069b,
        set_object_visible = 0x0750,
        destroy_object_with_fade = 0x09A2,
        disassociate_object = 0x0682,
        set_object_scaling = 0x08d2,
        set_actor_rotation_angles = 0x083e,
        is_actor_in_the_water = 0x04ad,
        create_pickup = 0x0213,
        create_pickup_with_ammo = 0x032b,
        is_pickup_picked_up = 0x0214,
        is_pickup_created = 0x09D1,
        destroy_pickup = 0x0215,
        set_event = 0x09C6,
        change_car_skin = 0x06ED,
        add_car_component = 0x06E7,
        is_component_available = 0x06EA,
        request_car_component = 0x06E9,
        remove_component = 0x06E8,
        unknown_arrow = 0x07e0,
        show_on_radar2 = 0x018b,
        open_garage = 0x0360,
        close_garage = 0x0361,
        find_ground_z = 0x02CE,
        put_car_at = 0x00AB,
        is_actor_crouching = 0x0597,
        is_ped_bounding_sphere_visible = 0x02CB,
        is_player_in_a_car = 0x0443,
        set_camera_pos = 0x03cb,
        set_actor_collision_detection = 0x0619,
        toggle_actor_cellphone = 0x0729,
        actor_task_sit = 0x06b0,
        actor_task_handsup = 0x5c4,
        actor_task_use_atm = 0x5c7,
        change_stat = 0x0629,
        unk_gang_war1 = 0x08A3,
        unk_gang_war2 = 0x0879,
        set_zone_owned_by = 0x076C,
        toggle_car_tires_vulnerable = 0x053f,
        set_fighting_style = 0x07fe,
        link_vehicle_to_interior = 0x0840,
        destroy_object = 0x0108,
        create_radar_marker_icon = 0x0570,
        put_trailer_on_cab = 0x893,
        detach_trailer_from_cab = 0x7AC,
        is_trailer_on_cab = 0x7AB,
        enable_heli_magnet = 0x0788,
        get_player_weapon_ammo = 0x0419,
        set_player_weapon_ammo = 0x017A,
        set_train_flag = 0x09CF,
        put_camera_on_vehicle = 0x0679,
        put_camera_on_actor = 0x067C,
        create_explosion_with_radius = 0x0948,
        set_car_numberplate = 0x0674,
        enable_zone_names = 0x09BA,
        remove_panel = 0x08DA,
        create_panel = 0x08D4,
        set_panel_column_data = 0x08DB,
        set_panel_column_width = 0x09DB,
        set_panel_row_enable = 0x08D9,
        get_panel_selected_row = 0x08D8,
        get_panel_active_row = 0x08D7,
        destroy_particle = 0x650,
        attach_particle_to_actor2 = 0x066a,
        make_particle_visible = 0x64c,
        create_property_pickup = 0x518,
        set_actor_not_react_to_gun_point = 0x350,
        set_actor_targetable = 0x568,
        set_actor_behaviour = 0x11a,
        set_actor_unk5 = 0x446,
        set_actor_dicision = 0x60B,
        walk_actor_to_point = 0x0211,
        damage_car = 0x730,
        set_helicopter_fly_to = 0x04A2,
        set_player_drunk_visuals = 0x052c,
        handling_responsiveness = 0x03fd
    }
}
